[package]
name = "roxy_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
syntect = "5.1.0"
roxy_core = { git = "https://github.com/kitsunecafe/roxy-core.git" }
clap = { version = "4.4.17", features = ["derive"] }
toml = "0.8.8"
tera = "1.19.1"

