[package]
name = "roxy_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
syntect = "5.1.0"
roxy_core = { path = "../roxy_core/" }
clap = { version = "4.4.17", features = ["derive"] }

